# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ITMO Students Raiting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ITMO Students Raiting
	pod 'SwiftSoup'

end
